### ISSUE TITLE
Toggling the terminal repeatedly causes segfault

### ISSUE THREAD

**Issue by jgmdev** [adamharrison/lite-xl-terminal#9]
segfault with terminal plugin after doing various consecutive toggles:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffff7f99f91 in terminal_output (terminal=0x555558b3ee80, 
    str=0x7fffffffb780 "\033[?2004h\033[0;97m\033[90;1mjgmdev@machine \033[36;1mplugins ±\033[0;32m|master \033[0;31m✗\033[0;32m|\033[32;1m→ \033[0m", len=98) at src/libterminal.c:922
922              view->buffer[view->cursor_y * terminal->columns + view->cursor_x] = (buffer_char_t){ view->cursor_styling, codepoint };
```
 here the backtrace:
```
#0  0x00007fffc7eb5f91 in terminal_output (terminal=0x555556115060, 
    str=0x7fffffffc290 "\033[?2004h\033[0;97m\033[90;1mjgmdev@machine \033[36;1mplugins ±\033[0;32m|master \033[0;31m✗\033[0;32m|\033[32;1m→ \033[0m\377\377\377\177", len=98) at src/libterminal.c:922
#1  0x00007fffc7eb609b in terminal_update (terminal=0x555556115060, callback=0x0, data=0x0) at src/libterminal.c:972
#2  0x00007fffc7eb71fb in f_terminal_update (L=0x7fffc4985c90) at src/libterminal.c:1276
#3  0x00007ffff7efeef6 in ?? () from /usr/lib/libluajit-5.1.so.2
#4  0x00007ffff7effd2c in ?? () from /usr/lib/libluajit-5.1.so.2
#5  0x00007ffff7effe9e in ?? () from /usr/lib/libluajit-5.1.so.2
#6  0x00007ffff7f11a73 in lua_pcall () from /usr/lib/libluajit-5.1.so.2
#7  0x00005555555917d3 in main (argc=1, argv=0x7fffffffdd88) at ../src/main.c:281
```
and here a backtrace when using PUC Lua
```
#0  0x00007ffff7f99f91 in terminal_output (terminal=0x555558b3ee80, 
    str=0x7fffffffb780 "\033[?2004h\033[0;97m\033[90;1mjgmdev@machine \033[36;1mplugins ±\033[0;32m|master \033[0;31m✗\033[0;32m|\033[32;1m→ \033[0m", len=98) at src/libterminal.c:922
#1  0x00007ffff7f9a09b in terminal_update (terminal=0x555558b3ee80, callback=0x0, data=0x0) at src/libterminal.c:972
#2  0x00007ffff7f9b1fb in f_terminal_update (L=0x55555808ffd8) at src/libterminal.c:1276
#3  0x00007ffff7f526db in ?? () from /usr/lib/liblua.so.5.4
#4  0x00007ffff7f61794 in ?? () from /usr/lib/liblua.so.5.4
#5  0x00007ffff7f54e94 in ?? () from /usr/lib/liblua.so.5.4
#6  0x00007ffff7f4d574 in ?? () from /usr/lib/liblua.so.5.4
#7  0x00007ffff7f4e5af in lua_resume () from /usr/lib/liblua.so.5.4
#8  0x00007ffff7f6b343 in ?? () from /usr/lib/liblua.so.5.4
#9  0x00007ffff7f6b427 in ?? () from /usr/lib/liblua.so.5.4
#10 0x00007ffff7f526db in ?? () from /usr/lib/liblua.so.5.4
#11 0x00007ffff7f61794 in ?? () from /usr/lib/liblua.so.5.4
#12 0x00007ffff7f54e94 in ?? () from /usr/lib/liblua.so.5.4
#13 0x00007ffff7f4d574 in ?? () from /usr/lib/liblua.so.5.4
#14 0x00007ffff7f4e5af in lua_resume () from /usr/lib/liblua.so.5.4
```
Workaround:
```diff
 static int f_terminal_update(lua_State* L){
   int status;
-  if (lua_type(L, 2) == LUA_TFUNCTION)
-    status = terminal_update(lua_toterminal(L, 1), chunk_update, L);
+  terminal_t* term = lua_toterminal(L, 1);
+  if (!term->views[0].buffer)
+    status = 0;
+  else if (lua_type(L, 2) == LUA_TFUNCTION)
+    status = terminal_update(term, chunk_update, L);
   else
-    status = terminal_update(lua_toterminal(L, 1), NULL, NULL);
+    status = terminal_update(term, NULL, NULL);
   lua_pushboolean(L, status != 0);
   return 1;
 }
```

**Comment by adamharrison** [comment]
Try c13d3829963514d9298db34a9402bd4d9b52dd92.

**Comment by jgmdev** [comment]
Thank you, that fixes the issue.
